-- Profile POC Database Schema
-- Runs automatically on first docker compose up

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- RAW DATA SNAPSHOTS (imported from production, read-only)
-- ============================================================

CREATE TABLE raw_schools (
  id SERIAL PRIMARY KEY,
  urn INTEGER UNIQUE NOT NULL,
  data JSONB NOT NULL,
  imported_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE raw_products (
  id SERIAL PRIMARY KEY,
  product_id TEXT UNIQUE NOT NULL,
  data JSONB NOT NULL,
  imported_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ENTITY PROFILES (LLM-generated, evolving schema)
-- ============================================================

CREATE TABLE entity_profiles (
  id SERIAL PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  entity_name TEXT,

  schema_version TEXT NOT NULL DEFAULT '1.0',
  structured_fields JSONB NOT NULL DEFAULT '{}',

  raw_data JSONB,
  profile_text TEXT,
  profile_embedding vector(1024),

  profiled_at TIMESTAMPTZ DEFAULT NOW(),
  profiled_by TEXT DEFAULT 'titan-v2',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(entity_type, entity_id)
);

CREATE INDEX idx_profiles_type ON entity_profiles(entity_type);
CREATE INDEX idx_profiles_entity ON entity_profiles(entity_type, entity_id);
CREATE INDEX idx_profiles_embedding ON entity_profiles
  USING hnsw (profile_embedding vector_cosine_ops);
CREATE INDEX idx_profiles_structured ON entity_profiles
  USING gin (structured_fields);

-- ============================================================
-- PRECOMPUTED SIMILARITIES
-- ============================================================

CREATE TABLE entity_similarities (
  id SERIAL PRIMARY KEY,
  entity_type TEXT NOT NULL,
  source_entity_id TEXT NOT NULL,
  similar_entity_id TEXT NOT NULL,

  similarity_score NUMERIC(5,4),
  structured_score NUMERIC(5,4),
  embedding_score NUMERIC(5,4),
  graph_score NUMERIC(5,4),

  explanation TEXT,

  computed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(entity_type, source_entity_id, similar_entity_id)
);

CREATE INDEX idx_similarities_lookup
  ON entity_similarities(entity_type, source_entity_id, similarity_score DESC);

-- ============================================================
-- PRODUCT ALTERNATIVES (imported from production)
-- ============================================================

CREATE TABLE raw_product_alternatives (
  id SERIAL PRIMARY KEY,
  product_id TEXT NOT NULL,
  alternative_product_id TEXT NOT NULL,
  imported_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(product_id, alternative_product_id)
);

CREATE INDEX idx_alternatives_product ON raw_product_alternatives(product_id);
CREATE INDEX idx_alternatives_alt ON raw_product_alternatives(alternative_product_id);

-- ============================================================
-- EDUCATIONAL IMPACT SCORES (imported from production)
-- ============================================================

CREATE TABLE raw_educational_impact (
  id SERIAL PRIMARY KEY,
  product_id TEXT UNIQUE NOT NULL,
  build_student_knowledge NUMERIC(5,2),
  improve_attainment NUMERIC(5,2),
  improve_teaching_efficiency NUMERIC(5,2),
  reduce_teacher_workload NUMERIC(5,2),
  improve_teacher_knowledge NUMERIC(5,2),
  imported_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- CHAT THREADS & MESSAGES (agentic chat persistence)
-- ============================================================

CREATE TABLE chat_threads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT,
  entity_context JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id UUID REFERENCES chat_threads(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT,
  tool_calls JSONB,
  tool_results JSONB,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_messages_thread ON chat_messages(thread_id, created_at);
CREATE INDEX idx_threads_updated ON chat_threads(updated_at DESC);

-- ============================================================
-- MATCH REPORTS (generated by agent)
-- ============================================================

CREATE TABLE match_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id UUID REFERENCES chat_threads(id),
  school_id TEXT NOT NULL,
  report_data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- USER RATINGS (business user match assessments)
-- ============================================================

CREATE TABLE user_ratings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_entity_id TEXT NOT NULL,
  target_entity_id TEXT NOT NULL,
  target_entity_type TEXT NOT NULL,
  star_rating INTEGER CHECK (star_rating BETWEEN 1 AND 5),
  rank_position INTEGER,
  shortlisted BOOLEAN DEFAULT false,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(source_entity_id, target_entity_id)
);

CREATE INDEX idx_ratings_source ON user_ratings(source_entity_id);
CREATE INDEX idx_ratings_shortlist ON user_ratings(source_entity_id, shortlisted) WHERE shortlisted = true;
